import axios from "axios";
import { getHeaders } from "../auth/authService";
const BASE="https://event-management-ticket-booking-system.onrender.com";
export const login=(d)=>axios.post(`${BASE}/login`,d);
export const changePassword=(d)=>axios.post(`${BASE}/changePassword`,d);
export const getProfile=()=>axios.get(`${BASE}/user/profile`,{headers:getHeaders()});
export const updateProfile=(d)=>axios.post(`${BASE}/user/updateProfile`,d,{headers:getHeaders()});
export const getDashboardStats=()=>axios.get(`${BASE}/admin/dashboardStats`,{headers:getHeaders()});
export const getUsers=()=>axios.get(`${BASE}/admin/users`,{headers:getHeaders()});
export const updateUserStatus=(d)=>axios.post(`${BASE}/admin/updateUserStatus`,d,{headers:getHeaders()});
export const getAdminCategories=()=>axios.get(`${BASE}/admin/categories`,{headers:getHeaders()});
export const addCategory=(d)=>axios.post(`${BASE}/admin/addCategory`,d,{headers:getHeaders()});
export const updateCategory=(d)=>axios.post(`${BASE}/admin/updateCategory`,d,{headers:getHeaders()});
export const deleteCategory=(id)=>axios.get(`${BASE}/admin/deleteCategory/${id}`,{headers:getHeaders()});
export const getAdminEvents=()=>axios.get(`${BASE}/admin/events`,{headers:getHeaders()});
export const addEvent=(d)=>axios.post(`${BASE}/admin/addEvent`,d,{headers:getHeaders()});
export const updateEvent=(d)=>axios.post(`${BASE}/admin/updateEvent`,d,{headers:getHeaders()});
export const deleteEvent=(id)=>axios.get(`${BASE}/admin/deleteEvent/${id}`,{headers:getHeaders()});
export const getBookings=()=>axios.get(`${BASE}/admin/bookings`,{headers:getHeaders()});
export const updateBooking=(d)=>axios.post(`${BASE}/admin/updateBooking`,d,{headers:getHeaders()});
export const getPayments=()=>axios.get(`${BASE}/admin/payments`,{headers:getHeaders()});
export const getReviews=()=>axios.get(`${BASE}/admin/reviews`,{headers:getHeaders()});
export const getComplaints=()=>axios.get(`${BASE}/admin/complaints`,{headers:getHeaders()});
export const resolveComplaint=(id)=>axios.post(`${BASE}/admin/resolveComplaint/${id}`,{},{headers:getHeaders()});
export const getAdminCateg=()=>axios.get(`${BASE}/categories`);
